[db.drivers.default]
driver = "mysql"
host = "127.0.0.1"
database = "dux"
username = "root"
password = "root"
port = 3306
prefix = "app_"

[redis.drivers.default]
host = "127.0.0.1"
port = 6379
password = ""
